endpoints:
  rpc: "http://localhost:26657"
  metrics: "http://localhost:26660/metrics"
  websocket: "ws://localhost:26657/websocket"

monitoring:
  poll_interval_ms: 200
  output_dir: "./block_timing_data/v5.1.2"
  enable_websocket: true
  log_file_path: "~/.layer/layer.log"

version:
  tag: "v5.1.2"
  
analysis:
  slow_block_threshold_std_dev: 2.0
  moving_average_window: 20
  
filters:
  min_height: null
  max_height: null
  track_message_types: ["MsgTip", "MsgSubmitValue", "MsgDelegate", "MsgCreateValidator"]

