# This is a TOML config file.
[endpoints]
    [endpoints.coinbase]
    url_template = "https://api.coinbase.com/v2/prices/{currency_pair}/spot"
    method = "GET"
    timeout = 5000
    [endpoints.coingecko]
    url_template = "https://api.coingecko.com/api/v3/simple/price?ids={coin_id}&vs_currencies=usd"
    method = "GET"
    timeout = 5000
    [endpoints.coinmarketcap]
    url_template = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?id={id}"
    method = "GET"
    timeout = 5000
    api_key = "${CMC_PRO_API_KEY}"
    headers = { Accept = "application/json", X-CMC_PRO_API_KEY = "api_key" }
    [endpoints.coinpaprika]
    url_template = "https://api.coinpaprika.com/v1/tickers/{coin_id}?quotes=USD"
    method = "GET"
    timeout = 5000
    [endpoints.crypto]
    url_template = "https://api.crypto.com/v2/public/get-ticker?instrument_name={instrument_name}"
    method = "GET"
    timeout = 5000
    [endpoints.curve]
    url_template = "https://prices.curve.finance/v1/usd_price/ethereum/{contract_address}"
    method = "GET"
    timeout = 5000
    [endpoints.osmosis]
    url_template = "https://lcd.osmosis.zone/osmosis/gamm/v1beta1/pools/{pool_id}"
    method = "GET"
    timeout = 5000
    [endpoints.sushiswapKatana]
    url_template = "https://api.sushi.com/price/v1/747474"
    method = "GET"
    timeout = 5000
    [endpoints.uniswapV3ethereum]
    url_template = "https://gateway.thegraph.com/api/{api_key}/subgraphs/id/5zvR82QoaXYFyDEKLZ9t6v9adgnptxYpKpSbxtgVENFV"
    method = "POST"
    timeout = 5000
    query = '''{"query": "{ token(id: \"{token_address}\") { derivedETH } }"}'''
    api_key = "${SUBGRAPH_API_KEY}"
    headers = { Content-Type = "application/json" }
    [endpoints.uniswapV4ethereum]
    url_template = "https://gateway.thegraph.com/api/{api_key}/subgraphs/id/DiYPVdygkfjDWhbxGSqAQxwBKmfKnkWQojqeM2rkLb3G"
    method = "POST"
    timeout = 5000
    query = '''{"query": "{ token(id: \"{token_address}\") { derivedETH } }"}'''
    api_key = "${SUBGRAPH_API_KEY}"
    headers = { Content-Type = "application/json" }
[rpc_endpoints]
    [rpc_endpoints.ethereum]
    urls = ["https://mainnet.infura.io/v3/${INFURA_API_KEY}", "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}", "https://rpc.ankr.com/eth"]

[queries]
    [queries.03731257e35c49e44b267640126358e5decebdd8f18b5e8f229542ec86e318cf]
    id = "03731257e35c49e44b267640126358e5decebdd8f18b5e8f229542ec86e318cf"
    aggregation_method = "median"
	max_spread_percent = 10.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.03731257e35c49e44b267640126358e5decebdd8f18b5e8f229542ec86e318cf.endpoints]]
        endpoint_type = "contract"
        response_path = []
        params = {  }
        market_id = "SUSDE-USD"
        handler = "susdeusd_handler"
		chain = "ethereum"
    [queries.05cddb6b67074aa61fcbe1d2fd5924e028bb699b506267df28c88f7deac4edc6]
    id = "05cddb6b67074aa61fcbe1d2fd5924e028bb699b506267df28c88f7deac4edc6"
    aggregation_method = "median"
	max_spread_percent = 50.000000
    min_responses = 2
    response_type = "ufixed256x18"
        [[queries.05cddb6b67074aa61fcbe1d2fd5924e028bb699b506267df28c88f7deac4edc6.endpoints]]
        endpoint_type = "coingecko"
        response_path = ["savings-dai", "usd"]
        params = { coin_id = "savings-dai" }
        market_id = "SDAI-USD"
        [[queries.05cddb6b67074aa61fcbe1d2fd5924e028bb699b506267df28c88f7deac4edc6.endpoints]]
        endpoint_type = "coinpaprika"
        response_path = ["quotes", "USD", "price"]
        params = { coin_id = "sdai-savings-dai" }
        market_id = "SDAI-USD"
        [[queries.05cddb6b67074aa61fcbe1d2fd5924e028bb699b506267df28c88f7deac4edc6.endpoints]]
        endpoint_type = "curve"
        response_path = ["data", "usd_price"]
        params = { contract_address = "0x83F20F44975D03b1b09e64809B757c47f942BEeA" }
        market_id = "SDAI-USD"
    [queries.0bc2d41117ae8779da7623ee76a109c88b84b9bf4d9b404524df04f7d0ca4ca7]
    id = "0bc2d41117ae8779da7623ee76a109c88b84b9bf4d9b404524df04f7d0ca4ca7"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.0bc2d41117ae8779da7623ee76a109c88b84b9bf4d9b404524df04f7d0ca4ca7.endpoints]]
        endpoint_type = "contract"
        response_path = []
        params = {  }
        market_id = "RETH-USD"
        handler = "reth_handler"
		chain = "ethereum"
    [queries.187f74d310dc494e6efd928107713d4229cd319c2cf300224de02776090809f1]
    id = "187f74d310dc494e6efd928107713d4229cd319c2cf300224de02776090809f1"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.187f74d310dc494e6efd928107713d4229cd319c2cf300224de02776090809f1.endpoints]]
        endpoint_type = "combined"
        response_path = []
        params = {  }
        handler = "susn_price"
		combined_sources = { coingecko = "rpc:coingecko", ethereum = "contract:ethereum", coinpaprika = "rpc:coinpaprika" }
		[queries.187f74d310dc494e6efd928107713d4229cd319c2cf300224de02776090809f1.endpoints.combined_config]
		    coingecko_params = { coin_id = "noon-usn" }
		    coingecko_response_path = ["noon-usn", "usd"]
		    coinpaprika_params = { coin_id = "usn1-noon-usn" }
		    coinpaprika_response_path = ["quotes", "USD", "price"]
		    max_spread_percent = 100.000000
		    min_responses = 1
    [queries.1962cde2f19178fe2bb2229e78a6d386e6406979edc7b9a1966d89d83b3ebf2e]
    id = "1962cde2f19178fe2bb2229e78a6d386e6406979edc7b9a1966d89d83b3ebf2e"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.1962cde2f19178fe2bb2229e78a6d386e6406979edc7b9a1966d89d83b3ebf2e.endpoints]]
        endpoint_type = "contract"
        response_path = []
        params = {  }
        market_id = "WSTETH-USD"
        handler = "wsteth_handler"
		chain = "ethereum"
    [queries.35155b44678db9e9e021c2cf49dd20c31b49e03415325c2beffb5221cf63882d]
    id = "35155b44678db9e9e021c2cf49dd20c31b49e03415325c2beffb5221cf63882d"
    aggregation_method = "median"
	max_spread_percent = 10.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.35155b44678db9e9e021c2cf49dd20c31b49e03415325c2beffb5221cf63882d.endpoints]]
        endpoint_type = "contract"
        response_path = []
        params = {  }
        market_id = "YTOKEN-USD"
        handler = "yieldfi_yusd_handler"
		chain = "ethereum"
    [queries.59ae85cec665c779f18255dd4f3d97821e6a122691ee070b9a26888bc2a0e45a]
    id = "59ae85cec665c779f18255dd4f3d97821e6a122691ee070b9a26888bc2a0e45a"
    aggregation_method = "median"
	max_spread_percent = 10.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.59ae85cec665c779f18255dd4f3d97821e6a122691ee070b9a26888bc2a0e45a.endpoints]]
        endpoint_type = "coingecko"
        response_path = ["susds", "usd"]
        params = { coin_id = "susds" }
        market_id = "SUSDS-USD"
    [queries.611fd0e88850bf0cc036d96d04d47605c90b993485c2971e022b5751bbb04f23]
    id = "611fd0e88850bf0cc036d96d04d47605c90b993485c2971e022b5751bbb04f23"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 2
    response_type = "ufixed256x18"
        [[queries.611fd0e88850bf0cc036d96d04d47605c90b993485c2971e022b5751bbb04f23.endpoints]]
        endpoint_type = "coingecko"
        response_path = ["stride-staked-atom", "usd"]
        params = { coin_id = "stride-staked-atom" }
        market_id = "stATOM-USD"
        [[queries.611fd0e88850bf0cc036d96d04d47605c90b993485c2971e022b5751bbb04f23.endpoints]]
        endpoint_type = "coinmarketcap"
        response_path = ["data", "21686", "quote", "USD", "price"]
        params = { id = "21686" }
        market_id = "stATOM-USD"
        [[queries.611fd0e88850bf0cc036d96d04d47605c90b993485c2971e022b5751bbb04f23.endpoints]]
        endpoint_type = "osmosis"
        response_path = ["pool"]
        params = { pool_id = "1136" }
        market_id = "stATOM-USD"
        handler = "osmosis_pool_price_handler"
		usd_via_id = 7
    [queries.76b504e33305a63a3b80686c0b7bb99e7697466927ba78e224728e80bfaaa0be]
    id = "76b504e33305a63a3b80686c0b7bb99e7697466927ba78e224728e80bfaaa0be"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 2
    response_type = "ufixed256x18"
        [[queries.76b504e33305a63a3b80686c0b7bb99e7697466927ba78e224728e80bfaaa0be.endpoints]]
        endpoint_type = "coingecko"
        response_path = ["tbtc", "usd"]
        params = { coin_id = "tbtc" }
        market_id = "TBTC-USD"
        [[queries.76b504e33305a63a3b80686c0b7bb99e7697466927ba78e224728e80bfaaa0be.endpoints]]
        endpoint_type = "coinmarketcap"
        response_path = ["data", "26133", "quote", "USD", "price"]
        params = { id = "26133" }
        market_id = "TBTC-USD"
        [[queries.76b504e33305a63a3b80686c0b7bb99e7697466927ba78e224728e80bfaaa0be.endpoints]]
        endpoint_type = "coinbase"
        response_path = ["data", "amount"]
        params = { currency_pair = "TBTC-USD" }
        market_id = "TBTC-USD"
    [queries.91513b15db3cef441d52058b24412957f9cc8645c53aecf39446ac9b0d2dcca4]
    id = "91513b15db3cef441d52058b24412957f9cc8645c53aecf39446ac9b0d2dcca4"
    aggregation_method = "median"
	max_spread_percent = 10.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.91513b15db3cef441d52058b24412957f9cc8645c53aecf39446ac9b0d2dcca4.endpoints]]
        endpoint_type = "combined"
        response_path = []
        params = {  }
        market_id = "VYUSD-USD"
        handler = "vyusd_price"
		combined_sources = { ethereum = "contract:ethereum" }
		[queries.91513b15db3cef441d52058b24412957f9cc8645c53aecf39446ac9b0d2dcca4.endpoints.combined_config]
		    max_spread_percent = 100.000000
		    min_responses = 1
    [queries.9874c1c7b7e76b78afdfdda6dcecef56edf6bf3d49d6d6ef2a98404ea2e04a59]
    id = "9874c1c7b7e76b78afdfdda6dcecef56edf6bf3d49d6d6ef2a98404ea2e04a59"
    aggregation_method = "median"
	max_spread_percent = 10.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.9874c1c7b7e76b78afdfdda6dcecef56edf6bf3d49d6d6ef2a98404ea2e04a59.endpoints]]
        endpoint_type = "contract"
        response_path = []
        params = {  }
        market_id = "YIELDFI-YETH-USD"
        handler = "yieldfi_yeth_handler"
		chain = "ethereum"
    [queries.ab30caa3e7827a27c153063bce02c0b260b29c0c164040c003f0f9ec66002510]
    id = "ab30caa3e7827a27c153063bce02c0b260b29c0c164040c003f0f9ec66002510"
    aggregation_method = "median"
	max_spread_percent = 10.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.ab30caa3e7827a27c153063bce02c0b260b29c0c164040c003f0f9ec66002510.endpoints]]
        endpoint_type = "combined"
        response_path = []
        params = {  }
        market_id = "SFRXUSD-USD"
        handler = "sfrxusd_price"
		combined_sources = { ethereum = "contract:ethereum", coingecko = "rpc:coingecko", curve = "rpc:curve", coinpaprika = "rpc:coinpaprika" }
		[queries.ab30caa3e7827a27c153063bce02c0b260b29c0c164040c003f0f9ec66002510.endpoints.combined_config]
		    coingecko_params = { coin_id = "frax" }
		    coingecko_response_path = ["frax", "usd"]
		    coinpaprika_params = { coin_id = "frax-frax" }
		    coinpaprika_response_path = ["quotes", "USD", "price"]
		    curve_params = { contract_address = "0x853d955aCEf822Db058eb8505911ED77F175b99e" }
		    curve_response_path = ["data", "usd_price"]
		    max_spread_percent = 50.000000
		    min_responses = 2
    [queries.d62f132d9d04dde6e223d4366c48b47cd9f90228acdc6fa755dab93266db5176]
    id = "d62f132d9d04dde6e223d4366c48b47cd9f90228acdc6fa755dab93266db5176"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 2
    response_type = "ufixed256x18"
        [[queries.d62f132d9d04dde6e223d4366c48b47cd9f90228acdc6fa755dab93266db5176.endpoints]]
        endpoint_type = "coingecko"
        response_path = ["lrt-squared", "usd"]
        params = { coin_id = "lrt-squared" }
        market_id = "KING-USD"
        [[queries.d62f132d9d04dde6e223d4366c48b47cd9f90228acdc6fa755dab93266db5176.endpoints]]
        endpoint_type = "coinmarketcap"
        response_path = ["data", "33695", "quote", "USD", "price"]
        params = { id = "33695" }
        market_id = "KING-USD"
        [[queries.d62f132d9d04dde6e223d4366c48b47cd9f90228acdc6fa755dab93266db5176.endpoints]]
        endpoint_type = "uniswapV4ethereum"
        response_path = ["data", "token", "derivedETH"]
        params = { token_address = "0x8f08b70456eb22f6109f57b8fafe862ed28e6040" }
        market_id = "KING-USD"
		usd_via_id = 1
    [queries.e010d752f28dcd2804004d0b57ab1bdc4eca092895d49160204120af11d15f3e]
    id = "e010d752f28dcd2804004d0b57ab1bdc4eca092895d49160204120af11d15f3e"
    aggregation_method = "median"
	max_spread_percent = 100.000000
    min_responses = 1
    response_type = "ufixed256x18"
        [[queries.e010d752f28dcd2804004d0b57ab1bdc4eca092895d49160204120af11d15f3e.endpoints]]
        endpoint_type = "coingecko"
        response_path = ["noble-dollar-usdn", "usd"]
        params = { coin_id = "noble-dollar-usdn" }
        market_id = "USDN-USD"
        [[queries.e010d752f28dcd2804004d0b57ab1bdc4eca092895d49160204120af11d15f3e.endpoints]]
        endpoint_type = "coinmarketcap"
        response_path = ["data", "36538", "quote", "USD", "price"]
        params = { id = "36538" }
        market_id = "USDN-USD"
